### ISSUE TITLE
Not start at all.

### ISSUE THREAD

**Issue by Zignet64** [guyrleech/VMware#2]
Hey, Guy Leech.
I'm coming in from the link:
https://communities.vmware.com/docs/DOC-38925

latest VMware powercli version installed
https://www.powershellgallery.com/packages/VMware.PowerCLI/

The [demo ](https://www.youtube.com/watch?v=zbT19Z7Xztw) shows a really interesting and useful script

But impossible to launch it (cf. debug.txt attached)
Is it possible to get help?

Thank you in advance

[debug.txt](https://github.com/guyrleech/VMware/files/4240464/debug.txt)

**Comment by guyrleech** [comment]
Translating the errors from debug.txt, I don't know what you are trying to run but it isn't this script. Have you saved the html rather than raw (PowerShell)? Please attach the file you are trying to run.

**Comment by Zignet64** [comment]
Then this is where I'm really sorry!
Yes, it was late and I completely fucked up the download of the file.
I just tested the clone works perfectly on the first try ! :) 
Thanks a lot for working and sharing this very useful script ! 
Regards.
